services:
  ui:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    command: ["npm", "run", "start"]
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ui.rule=HostRegexp(`oauth.doc.lvh.me`)'
      - 'traefik.http.routers.ui.entrypoints=web'
      - 'traefik.http.services.ui.loadbalancer.server.port=9030'
    networks:
      - localnet

  ui-prod:
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ui-prod.rule=HostRegexp(`oauth.doc.prod.lvh.me`)'
      - 'traefik.http.routers.ui-prod.entrypoints=web'
      - 'traefik.http.services.ui-prod.loadbalancer.server.port=9031'
    networks:
      - localnet

  traefik:
    image: traefik:v3
    hostname: traefik
    command:
      - '--api.dashboard=true'
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.watch=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.lvh.me`)'
      - 'traefik.http.routers.traefik.service=api@internal'
    networks:
      - localnet
    ports:
      - "80:80"    # HTTP
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  localnet: