name: Build

on:
  release:
    types: [ released ]

env:
  IMAGE_NAME: ficrypt/oauth-doc
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          FULL_IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          echo $FULL_IMAGE_NAME
          docker build -f ./Dockerfile -t $FULL_IMAGE_NAME .
          docker push $FULL_IMAGE_NAME

      - name: Cleanup
        env:
          FULL_IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          docker rmi $FULL_IMAGE_NAME

